include("mono.jl")
#include("ncmono.jl")
include("poly.jl")
include("rational.jl")
include("measure.jl")
include("exp.jl")
include("promote.jl")
include("comp.jl")
#include("nccomp.jl")
include("alg.jl")
#include("ncalg.jl")
include("diff.jl")
#include("subs.jl")
include("algebraicset.jl")
include("hash.jl")
include("div.jl")

include("show.jl")

#include("example1.jl")
#include("example2.jl")
