include("zip.jl")
include("mono.jl")
include("poly.jl")
include("rational.jl")
include("promote.jl")
include("comp.jl")
include("alg.jl")
include("diff.jl")
include("subs.jl")
include("hash.jl")
include("div.jl")
include("norm.jl")
include("var.jl")

include("show.jl")

include("example1.jl")
include("example2.jl")
