include("zip.jl")
include("variable.jl")
include("monomial.jl")
include("polynomial.jl")
include("rational.jl")
include("promote.jl")
include("comparison.jl")
include("algebra.jl")
include("differentiation.jl")
include("substitution.jl")
include("hash.jl")
include("division.jl")
include("norm.jl")

include("show.jl")

include("example1.jl")
include("example2.jl")
