# From MultivariateBases/src/interface.jl

"""
    maxdegree_basis(basis::SA.AbstractBasis, maxdegree::Int)

Return the explicit version of `basis` generating all polynomials of degree up to
`maxdegree`.
"""
function maxdegree_basis end

"""
    explicit_basis_covering(basis::SA.AbstractBasis, target::SA.ExplicitBasis)

Return the minimal basis of type `B` that can generate all polynomials generated by
the basis `target`.
"""
function explicit_basis_covering end
